/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.sorts;

import java.util.Random;

/**
 *
 * @author Admin
 */
public class SortsView extends javax.swing.JFrame {

    /**
     * Creates new form SortsView
     */
    public SortsView() {
        initComponents();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        GrupoOpcoes = new javax.swing.ButtonGroup();
        GrupoSorts = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        PanelOptions = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        btn10d = new javax.swing.JRadioButton();
        btn100d = new javax.swing.JRadioButton();
        btn1000d = new javax.swing.JRadioButton();
        jSeparator1 = new javax.swing.JSeparator();
        jButton1 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtDestino = new javax.swing.JTextArea();
        jComboBox1 = new javax.swing.JComboBox<>();
        rbtSelectedSort = new javax.swing.JRadioButton();
        rbtInsertSort = new javax.swing.JRadioButton();
        rbtMargeSort = new javax.swing.JRadioButton();
        rbtQuickSort = new javax.swing.JRadioButton();
        btnReordenar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel1.setText("Ordenação de Vetores");

        PanelOptions.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 2, 12)); // NOI18N
        jLabel2.setText("Opções:");

        GrupoOpcoes.add(btn10d);
        btn10d.setText("10 digitos");

        GrupoOpcoes.add(btn100d);
        btn100d.setText("100 digitos");

        GrupoOpcoes.add(btn1000d);
        btn1000d.setText("1000 digitos");

        jButton1.setText("Gerar Vetor");

        javax.swing.GroupLayout PanelOptionsLayout = new javax.swing.GroupLayout(PanelOptions);
        PanelOptions.setLayout(PanelOptionsLayout);
        PanelOptionsLayout.setHorizontalGroup(
            PanelOptionsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSeparator1)
            .addGroup(PanelOptionsLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(PanelOptionsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, 193, Short.MAX_VALUE)
                    .addGroup(PanelOptionsLayout.createSequentialGroup()
                        .addGroup(PanelOptionsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(btn10d)
                            .addComponent(btn100d)
                            .addComponent(btn1000d))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        PanelOptionsLayout.setVerticalGroup(
            PanelOptionsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelOptionsLayout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btn10d)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btn100d)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btn1000d)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton1)
                .addGap(0, 16, Short.MAX_VALUE))
        );

        txtDestino.setColumns(20);
        txtDestino.setLineWrap(true);
        txtDestino.setRows(5);
        jScrollPane1.setViewportView(txtDestino);

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Ascendente", "Descendente" }));

        GrupoSorts.add(rbtSelectedSort);
        rbtSelectedSort.setText("SelectedSort");

        GrupoSorts.add(rbtInsertSort);
        rbtInsertSort.setText("InserSort");

        GrupoSorts.add(rbtMargeSort);
        rbtMargeSort.setText("MergeSort");

        GrupoSorts.add(rbtQuickSort);
        rbtQuickSort.setText("QuickSort");

        btnReordenar.setText("Reordenar");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 954, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 199, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(PanelOptions, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(rbtSelectedSort, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(rbtInsertSort, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(rbtMargeSort)
                                .addGap(18, 18, 18)
                                .addComponent(rbtQuickSort))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btnReordenar)))))
                .addContainerGap(15, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(PanelOptions, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(rbtSelectedSort)
                            .addComponent(rbtInsertSort)
                            .addComponent(rbtMargeSort)
                            .addComponent(rbtQuickSort))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnReordenar))
                        .addGap(8, 8, 8)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 192, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(53, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnGerarVetorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGerarVetorActionPerformed
        // TODO add your handling code here:
        Random rand = new Random();
        txtDestino.setText(" ");
        if (btn10d.isSelected() == true) {
            int[] arr = new int[10];
            for (int i = 0; i < arr.length; i++) {
                arr[i] = rand.nextInt(99);
                txtDestino.append(String.valueOf(arr[i]) + ", ");

            }
        } else if (btn100d.isSelected() == true) {
            int[] arr = new int[100];
            for (int i = 0; i < arr.length; i++) {
                arr[i] = rand.nextInt(99);
                txtDestino.append(String.valueOf(arr[i]) + ", ");

            }

        } else if (btn1000d.isSelected() == true) {
            int[] arr = new int[1000];
            for (int i = 0; i < arr.length; i++) {
                arr[i] = rand.nextInt(99);
                txtDestino.append(String.valueOf(arr[i]) + ", ");
            }
        }
    }//GEN-LAST:event_btnGerarVetorActionPerformed

    private void btnReordenarVetorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnReordenarVetorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnReordenarVetorActionPerformed

    private void btn10dActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn10dActionPerformed
        // TODO add your handling code here:


    }//GEN-LAST:event_btn10dActionPerformed

    private void btn100dActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn100dActionPerformed
        // TODO add your handling code here:

    }//GEN-LAST:event_btn100dActionPerformed

    private void btn1000dActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn1000dActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btn1000dActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SortsView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SortsView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SortsView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SortsView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new SortsView().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup GrupoOpcoes;
    private javax.swing.ButtonGroup GrupoSorts;
    private javax.swing.JPanel PanelOptions;
    private javax.swing.JRadioButton btn1000d;
    private javax.swing.JRadioButton btn100d;
    private javax.swing.JRadioButton btn10d;
    private javax.swing.JButton btnReordenar;
    private javax.swing.JButton jButton1;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JRadioButton rbtInsertSort;
    private javax.swing.JRadioButton rbtMargeSort;
    private javax.swing.JRadioButton rbtQuickSort;
    private javax.swing.JRadioButton rbtSelectedSort;
    private javax.swing.JTextArea txtDestino;
    // End of variables declaration//GEN-END:variables
}
